---
title: "04_Analyze_Stochastic_Models"
author: "Julin Maloof"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(patchwork)
library(here)
library(future)
library(furrr)
plan(multisession(workers=4))
```

```{r}
#mem.maxVSize(36000)
simulation.list <- readRDS(here("Sim_Pop" , "output", "simpop_100sims_100gen_2025-09-29.Rds"))
```

currently only keep last week of data from sims so this isn't needed
```{r, eval = FALSE}
#92 seconds
system.time({
simulation.list.small <- future_map(simulation.list, function(sim) {
  sim <- sim %>% select(-seed) %>%
    mutate(pop = map(pop, \(x) filter(x, week==max(week)))) 
},
  .options = furrr_options(seed = TRUE) ) 
})
rm(simulation.list)
```

```{r}
system.time(
 # sims.df <- bind_rows(simulation.list.small, .id = "sim")
    sims.df <- bind_rows(simulation.list, .id = "sim")

)

rm(simulation.list)

# this takes a lot longer than system.time() reports for some reason
system.time(sims.df <- sims.df %>% unnest(pop))

head(sims.df)
```
NOT SURE IF POPSIZE IS GETTING CALCULATED CORRECTLY..HOW ARE THOSE EMPTY DATA FRAMES GETTING HANDLED?

summary stats
```{r}
system.time({
sims.summary <- sims.df %>%
      group_by(sim, gen) %>%
      summarize(popSize = sum(y1surv),
        across( c(germinated, established, y1surv, size, flowered, fruitPerPlant_pheno), 
               \(x) mean(x, na.rm = TRUE)),
        .groups = "drop"
      )
})
sims.summary
```
```{r}
summary(sims.summary)
```

```{r, fig.height=7, fig.width=9}
sims.summary %>%
  pivot_longer(-c(sim, gen), names_to = "trait", values_to = "value") %>%
  ggplot(aes(x=gen, y=value)) +
  geom_line(alpha=.05, aes(group=sim)) +
  geom_smooth(se = FALSE) +
  facet_wrap(~trait, scales="free_y")
```

```{r}
sims.summary %>%
  ggplot(aes(x=gen, y=popSize)) +
  geom_line(alpha=.05, aes(group=sim)) +
  geom_smooth(se = FALSE)
```

