---
title: "04_Analyze_Stochastic_Models"
author: "Julin Maloof"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This script is set up to handle the "old" data structure that contains all individuals in all generations.  See script 04_new_... for processing summary files.  Also this script may need minor updates to handle the current version of the "old" data structure.

```{r}
library(tidyverse)
library(patchwork)
library(here)
library(future)
library(furrr)
plan(multisession(workers=4))
```


```{r}
#mem.maxVSize(36000)
sims.df <- readRDS(here("Sim_Pop" , "output", "simpop_all_7sims_10gen_2025-10-06.Rds"))
```

```{r}
# this takes a lot longer than system.time() reports for some reason
system.time({sims.df <- sims.df %>% 
              select(-seed) %>% 
              unnest(pop) %>%
              select(-ends_with("_geno"))
})
  

head(sims.df)
```
NOT SURE IF POPSIZE IS GETTING CALCULATED CORRECTLY..HOW ARE THOSE EMPTY DATA FRAMES GETTING HANDLED?

summary stats
```{r}
system.time({
sims.summary <- sims.df %>%
      group_by(sim, gen) %>%
      summarize(popSize = sum(y1surv),
        across( c(germinated, established, y1surv, size, flowered, fruitPerPlant_pheno), 
               \(x) mean(x, na.rm = TRUE)),
        .groups = "drop"
      )
})

# fill in popSize = 0 where there is missing data
sims.summary <- sims.summary %>% 
  expand(sim, gen) %>% 
  left_join(sims.summary) %>%
  mutate(popSize = replace_na(popSize, 0))
```

```{r, fig.height=7, fig.width=9}
sims.summary %>%
  pivot_longer(-c(sim, gen), names_to = "trait", values_to = "value") %>%
  ggplot(aes(x=gen, y=value)) +
  geom_line(alpha=.05, aes(group=sim)) +
  geom_smooth(se = FALSE) +
  facet_wrap(~trait, scales="free_y")
```

```{r}
sims.summary %>%
  ggplot(aes(x=gen, y=popSize)) +
  geom_line(alpha=.1, aes(group=sim)) +
  geom_smooth(se = FALSE)
```

